### ISSUE TITLE
How do I add Azure OpenAI

### ISSUE THREAD

**Issue by way-ww** [LibreChat-AI/librechat-config-yaml#36]
Sorry，I am a beginner. How do I add Azure OpenAI？I found Azure OpenAI in the demo, but it seems that the YAML files in the repo are not configured.

**Comment by fuegovic** [comment]
In the demo, Azure is set to "user provided" with the environment variables. 

The correct method to configure Azure in the yaml file is detailed here: https://www.librechat.ai/docs/configuration/azure
